### ISSUE TITLE
Mask data type is float

### ISSUE THREAD

**Issue by cookpa** [ftdc-picsl/T1wPreprocessing#4]
I think we want the brain mask data type to be 'uchar'. Some software doesn't care but software that does care generally likes uchar.

@caugolm @ins0mniac2 does this sound good?

**Comment by cookpa** [comment]
FYI I had intended to do this from the start, but I forgot to add it into the last step so the masks are currently float

**Comment by ins0mniac2** [comment]
Sounds good to me.
